import "./globals.css";
import Main from "./Main";

export const metadata = {
  icons: {
    icon: "/EscudoUniminuto.webp",
    shortcut: "/EscudoUniminuto.webp",
    apple: "/EscudoUniminuto.webp",
    other: {
      rel: "shortcut icon",
      url: "/EscudoUniminuto.webp",
    },
  },
  title: "SYGESAUNIV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Main>{children}</Main>
    </html>
  );
}
