import "./globals.css";
import Main from "./Main";

export const metadata = {
  title: "SYGESAUNIV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Main>{children}</Main>
    </html>
  );
}
